name: BVS
favicon: null
layout_spectrum: 0.23672
typography_spectrum: 0.44669
title: 'Grafische weergave BVS '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.37888726545497775
  lightness: 0.15633177710697055
  saturation: 0.6673131184652448
  rhythmicContrast: 0.6895884482655674
purpose: []
